using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Agvise.Api.Models
{
    public static class ValidValues
    {
        public static readonly Dictionary<string, string> StateAndProvinces = new Dictionary<string, string>()
        {
            { "AL", "Alabama" },
            { "AK", "Alaska" },
            { "AB", "Alberta" },
            { "AZ", "Arizona" },
            { "AR", "Arkansas" },
            { "BC", "British Columbia" },
            { "CA", "California" },
            { "CO", "Colorado" },
            { "CT", "Connecticut" },
            { "DE", "Delaware" },
            { "DC", "District of Columbia" },
            { "FL", "Florida" },
            { "GA", "Georgia" },
            { "HI", "Hawaii" },
            { "ID", "Idaho" },
            { "IL", "Illinois" },
            { "IN", "Indiana" },
            { "IA", "Iowa" },
            { "KS", "Kansas" },
            { "KY", "Kentucky" },
            { "LA", "Louisiana" },
            { "ME", "Maine" },
            { "MB", "Manitoba" },
            { "MD", "Maryland" },
            { "MA", "Massachusetts" },
            { "MI", "Michigan" },
            { "MN", "Minnesota" },
            { "MS", "Mississippi" },
            { "MO", "Missouri" },
            { "MT", "Montana" },
            { "NE", "Nebraska" },
            { "NV", "Nevada" },
            { "NB", "New Brunswick" },
            { "NH", "New Hampshire" },
            { "NJ", "New Jersey" },
            { "NM", "New Mexico" },
            { "NY", "New York" },
            { "NL", "Newfoundland and Labrador" },
            { "NC", "North Carolina" },
            { "ND", "North Dakota" },
            { "NT", "Northwest Territories" },
            { "NS", "Nova Scotia" },
            { "NU", "Nunavut" },
            { "OH", "Ohio" },
            { "OK", "Oklahoma" },
            { "ON", "Ontario" },
            { "OR", "Oregon" },
            { "PA", "Pennsylvania" },
            { "PE", "Prince Edward Island" },
            { "QC", "Quebec" },
            { "RI", "Rhode Island" },
            { "SK", "Saskatchewan" },
            { "SC", "South Carolina" },
            { "SD", "South Dakota" },
            { "TN", "Tennessee" },
            { "TX", "Texas" },
            { "UT", "Utah" },
            { "VT", "Vermont" },
            { "VA", "Virginia" },
            { "WA", "Washington" },
            { "WV", "West Virginia" },
            { "WI", "Wisconsin" },
            { "WY", "Wyoming" },
            { "YT", "Yukon" }
        };

        public static readonly List<string> PKApplicationValues = new List<string>()
        {
            "Band",
            "Band/Maint",
            "Broadcast",
            "Broadcast/Maint",
            "University",
            "Centrol",
        };

        public static readonly List<string> PhosphorusOptions = new List<string>()
        {
            "Olsen",
            "Bray",
            "Olsen & Bray",
        };

        public static readonly List<string> Crops = new List<string>()
        {
            "Alfalfa",
            "Alfalfa Seed",
            "Barley",
            "Barley-Feed",
            "Barley-Malting",
            "Barley-Peas",
            "Beans-Edible",
            "Beans-Navy",
            "Beans-Pinto",
            "Brome Grass Seed",
            "Buckwheat",
            "Canary Seed",
            "Cane",
            "Canola-bu",
            "Canola-lb",
            "Carrots",
            "Chickpeas",
            "Clover or Trefoil",
            "Corn NP/CP = .10",
            "Corn NP/CP = .15",
            "Corn NP/CP = .20",
            "Corn/Soybeans",
            "Corn-Grain",
            "Corn-Silage",
            "Corn-Sweet",
            "Cotton",
            "Crambe",
            "Durum",
            "Faba Beans",
            "Fallow",
            "Flax",
            "Grapes-Established",
            "Grass Seed",
            "Grass/Alfalfa",
            "Grass/Pasture",
            "Hay Barley",
            "Lawns",
            "Lentils",
            "Millet-Grain",
            "Milo",
            "Mustard",
            "Oat Silage",
            "Oats",
            "Oats-Barley",
            "Oats-Peas",
            "Onions",
            "Peanuts",
            "Peas-Field",
            "Peas-Green",
            "Pop Corn",
            "Potatoes",
            "Potatoes-Chip",
            "Potatoes-Irr.",
            "Rye",
            "S. Beets 130/100",
            "S. Beets 6 lbs",
            "S. Beets 7 lbs",
            "Safflower",
            "Sidney Sugar",
            "SMBSC Beets",
            "Sorghum-Grain",
            "Sorghum-Hay",
            "Sorghum-Silage",
            "Soybeans",
            "Sunflower",
            "Timothy",
            "Triticale",
            "Veg. Garden",
            "Wheat-High Pro.",
            "Wheat-Low Pro.",
            "Wheat-Spring",
            "Wheat-Winter"
        };

        public static readonly List<string> AnalysisOptions = new List<string>()
        {
            "A",
            "Alafalfa",
            "ALFALFA",
            "B",
            "C",
            "C1",
            "C3",
            "C5",
            "CANOLA/SUNFLOWER",
            "Canola/Sunflowers",
            "CZ",
            "CZS",
            "DEALER DEFAULT",
            "DEALER DEFAULT",
            "E",
            "EZ",
            "EZS",
            "F",
            "N",
            "N,P",
            "N,P,K",
            "N,P,K,OM",
            "N,P,K,pH,OM,Zn",
            "N,P,K,pH,OM,Zn,S",
            "N,P,K,Zn",
            "N,P,K,Zn,OM",
            "N,P,K,Zn,S,Salts",
            "Option A",
            "Option B",
            "Option C",
            "Option C1",
            "Option C3",
            "Option C5",
            "Option CZ",
            "Option CZS",
            "Option E",
            "Option EZ",
            "Option EZS",
            "Option F",
            "Option T (no N)",
            "Option T (with N)",
            "Other",
            "P,K,pH,Buffer",
            "P,K,pH,OM",
            "P,K,pH,OM,Buffer",
            "P,K,pH,OM,CEC",
            "P,K,pH,OM,Zn",
            "P,K,pH,OM,Zn,CEC",
            "P,K,pH,OM,Zn,S",
            "P,K,pH,Zn",
            "POTATO",
            "Potato",
            "Row Crop",
            "ROW CROP",
            "SMALL GRAIN",
            "Small Grain",
            "Soy Bean (North)",
            "Soybean (South)",
            "SOYBEANS-NORTH",
            "SOYBEANS-SOUTH",
            "SUGAR BEET",
            "Sugar Beet",
            "T"
        };

        public static readonly List<string> AdditionalAnalysisOptions = new List<string>()
        {
            "Boron",
            "Buffer pH",
            "Calcium",
            "Carbonates",
            "Chloride",
            "Copper",
            "Iron",
            "Magnesium",
            "Manganese",
            "Nitrogen",
            "Organic Matter",
            "pH",
            "Phosphorus",
            "Potassium",
            "Salts",
            "Sodium",
            "Sulfur",
            "Texture",
            "Zinc"
        };
    }
}
